### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by MYlindaxia2** [Sprinklegcy/BigData#3]
大佬您好，我去网站上看了一下。数据集太多了不知道用哪些，想问问您这里还有您写代码时的数据集嘛？

**Comment by lutgcy** [comment]
https://github.com/lutgcy/BigData-Spark/issues/2
链接: https://pan.baidu.com/s/1zRKSyD5DE_7o9u8Y_kkfWQ 提取码: xtn2 复制这段内容后打开百度网盘手机App，操作更方便哦
[https://opengraph.githubassets.com/d088cdc9ec03928cf161f5c91385082a16d62be4bf03d4c6e2d86b49ff8ef8ca/lutgcy/BigData-Spark/issues/2]<https://github.com/lutgcy/BigData-Spark/issues/2>
关于数据集 ・ Issue #2 ・ lutgcy/BigData-Spark<https://github.com/lutgcy/BigData-Spark/issues/2>
你好，请问可以发一下数据集的下载链接吗，data.gov上好多气象数据
github.com

________________________________
发件人: ***@***.*** ***@***.***> 代表 MYlindaxia2 ***@***.***>
发送时间: 2024年1月1日 19:56
收件人: lutgcy/BigData-Spark ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [lutgcy/BigData-Spark] 关于数据集 (Issue #3)


Closed #3<https://github.com/lutgcy/BigData-Spark/issues/3> as completed.

―

**Comment by MYlindaxia2** [comment]
谢谢大佬，之前在截图里面找到了数据集的详细名称所以把issue关闭了。今天上来看到回复还是很感谢大佬！
